### ISSUE TITLE
GUI doesn't work on mobile

### ISSUE THREAD

**Issue by carlo-theunissen** [carloboy7/UrbanRoad#13]
It is not possible to use the gui with a mobile phone.
The code has to detect when someone finger is above a gui element. 

**Don't use the unity gui elements**
They are used right now, but they don't work!

**Comment by KLiebregts** [comment]
![screenshot_2016-03-19-13-20-31 1](https://cloud.githubusercontent.com/assets/9352221/13898564/b8dbbbfa-edd5-11e5-95fd-e314271068e8.png)

Hud changes with screen size (since i have it still on rotate i know) but useing the hud like playing on your mobile is still not possible. 

I find the hud a litle to small though.

**Comment by WouterStrangeDuck** [comment]
i think we made the current hud for pc and not mobile, the hud will be bigger. well look into this on monday
